@echo off
powershell -Command "& {iwr -useb https://raw.githubusercontent.com/thororen1234/extra/refs/heads/main/Spicetify.ps1 | iex}"

powershell -Command "& {Write-Host 'Removing Old External-Jukebox.'}"
powershell -Command "& {rm -r $env:APPDATA\spicetify\CustomApps\external-jukebox}"
powershell -Command "& {Write-Host 'Downloading External-Jukebox.zip'}"
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/Pithaya/spicetify-apps-dist/archive/refs/heads/dist/eternal-jukebox.zip' -OutFile $env:APPDATA\external-jukebox.zip | Invoke-Expression}"
powershell -Command "& {Write-Host 'Downloaded External-Jukebox.zip'}"
powershell -Command "& {Expand-Archive -Path $env:APPDATA/external-jukebox.zip -DestinationPath $env:APPDATA\spicetify\CustomApps}"
powershell -Command "& {Write-Host 'Unzipped External-Jukebox.zip'}"
powershell -Command "& {rm -r -fo $env:APPDATA/external-jukebox.zip}"
powershell -Command "& {Write-Host 'Removed External-Jukebox.zip'}"
powershell -Command "& {mv $env:APPDATA\spicetify\CustomApps\spicetify-apps-dist-dist-eternal-jukebox $env:APPDATA\spicetify\CustomApps\external-jukebox}"
powershell -Command "& {Write-Host 'Moved External-Jukebox into the correct folder.'}"
powershell -Command "& {spicetify config custom_apps external-jukebox}"
powershell -Command "& {Write-Host 'Enabled External-Jukebox in Spicetifys config.'}"

powershell -Command "& {Write-Host 'Removing Old Better-Local-Files.'}"
powershell -Command "& {rm -r $env:APPDATA\spicetify\CustomApps\better-local-files}"
powershell -Command "& {Write-Host 'Downloading Better-Local-Files.zip'}"
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/Pithaya/spicetify-apps-dist/archive/refs/heads/dist/better-local-files.zip' -OutFile $env:APPDATA\better-local-files.zip | Invoke-Expression}"
powershell -Command "& {Write-Host 'Downloaded Better-Local-Files.zip'}"
powershell -Command "& {Expand-Archive -Path $env:APPDATA/better-local-files.zip -DestinationPath $env:APPDATA\spicetify\CustomApps}"
powershell -Command "& {Write-Host 'Unzipped Better-Local-Files.zip'}"
powershell -Command "& {rm -r -fo $env:APPDATA/better-local-files.zip}"
powershell -Command "& {Write-Host 'Removed Better-Local-Files.zip'}"
powershell -Command "& {mv $env:APPDATA\spicetify\CustomApps\spicetify-apps-dist-dist-better-local-files $env:APPDATA\spicetify\CustomApps\better-local-files}"
powershell -Command "& {Write-Host 'Moved Better-Local-Files into the correct folder.'}"
powershell -Command "& {spicetify config custom_apps better-local-files}"
powershell -Command "& {Write-Host 'Enabled Better-Local-Files in Spicetifys config.'}"

powershell -Command "& {Write-Host 'Removing Old Combined-Playlists.'}"
powershell -Command "& {rm -r $env:APPDATA\spicetify\CustomApps\combined-playlists}"
powershell -Command "& {Write-Host 'Downloading Combined-Playlists.zip'}"
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/jeroentvb/spicetify-combined-playlists/archive/refs/heads/dist.zip' -OutFile $env:APPDATA\combined-playlists.zip | Invoke-Expression}"
powershell -Command "& {Write-Host 'Downloaded Combined-Playlists.zip'}"
powershell -Command "& {Expand-Archive -Path $env:APPDATA/combined-playlists.zip -DestinationPath $env:APPDATA\spicetify\CustomApps}"
powershell -Command "& {Write-Host 'Unzipped Combined-Playlists.zip'}"
powershell -Command "& {rm -r -fo $env:APPDATA/combined-playlists.zip}"
powershell -Command "& {Write-Host 'Removed Combined-Playlists.zip'}"
powershell -Command "& {mv $env:APPDATA\spicetify\CustomApps\spicetify-combined-playlists-dist\combined-playlists $env:APPDATA\spicetify\CustomApps}"
powershell -Command "& {Write-Host 'Moved Combined-Playlists into the correct folder.'}"
powershell -Command "& {rm -r -fo $env:APPDATA\spicetify\CustomApps\spicetify-combined-playlists-dist}"
powershell -Command "& {Write-Host 'Deleted old Combined-Playlists Folder.'}"
powershell -Command "& {spicetify config custom_apps combined-playlists}"
powershell -Command "& {Write-Host 'Enabled Combined-Playlists in Spicetifys config.'}"

powershell -Command "& {Write-Host 'Removing Old Better-Library.'}"
powershell -Command "& {rm -r $env:APPDATA\spicetify\CustomApps\better-library}"
powershell -Command "& {Write-Host 'Downloading Better-Library.zip'}"
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/Sowgro/betterLibrary/archive/refs/heads/main.zip' -OutFile $env:APPDATA\better-library.zip | Invoke-Expression}"
powershell -Command "& {Write-Host 'Downloaded Better-Library.zip'}"
powershell -Command "& {Expand-Archive -Path $env:APPDATA/better-library.zip -DestinationPath $env:APPDATA\spicetify\CustomApps}"
powershell -Command "& {Write-Host 'Unzipped Better-Library.zip'}"
powershell -Command "& {rm -r -fo $env:APPDATA/better-library.zip}"
powershell -Command "& {Write-Host 'Removed Better-Library.zip'}"
powershell -Command "& {mv $env:APPDATA\spicetify\CustomApps\betterLibrary-main\CustomApps\betterLibrary $env:APPDATA\spicetify\CustomApps\better-library}"
powershell -Command "& {Write-Host 'Moved Better-Library into the correct folder.'}"
powershell -Command "& {rm -r -fo $env:APPDATA\spicetify\CustomApps\betterLibrary-main}"
powershell -Command "& {Write-Host 'Deleted old Better-Library Folder.'}"
powershell -Command "& {spicetify config custom_apps better-library}"
powershell -Command "& {Write-Host 'Enabled Better-Library in Spicetifys config.'}"

powershell -Command "& {spicetify apply}"

powershell -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/thororen1234/extra/refs/heads/main/BlockTheSpot.ps1' | Invoke-Expression}"

pause
exit /b
